// Swap to your generated files (e.g. "/assets/sky.webp"). See PROMPTS.md.
export const A = {
  herotab: "/assets/hero2.png",
  sky: "/assets/sky.png",
  far: "/assets/far.png",
  near: "/assets/image.png",
  about: "/assets/imambara.png",
  venue: "/assets/venue.png",
  hacker: "/assets/hacker.png",
  person: "/assets/silhouette.png",
  logo: "/assets/logo.png",
  bgAbout: "/assets/bg-about.png",
  bgCount: "/assets/bg-count.png",
  bgExpect: "/assets/bg-expect.png",
  bgFormat: "/assets/bg-format.png",
  bgAgenda: "/assets/bg-agenda.png",
  bgSpeakers: "/assets/bg-speakers.png",
  bgCtf: "/assets/bg-ctf.png",
  bgLegacy: "/assets/bg-legacy.png",
  bgSponsors: "/assets/bg-sponsors.png",
  bgFaq: "/assets/bg-faq.png",
  bgFooter: "/assets/bg-footer.png",
  bgImpact: "/assets/bg-impact.png",
  bgAud: "/assets/bg-aud.png",
  logo2: "/assets/logo-w.png",
  speakerAbhiraj: "/speakers/abhiraj.png",
  speakerZuhaib: "/speakers/zuhaib.png",
  speakerKishan: "/speakers/kishan.png",
  sponsorInmobi: "/sponsors/inmobi.png",
  sponsorProdigy: "/sponsors/prodigy.png",
  sponsorOsen: "/sponsors/OSEN.png",
  sponsorCodevirus: "/sponsors/codevirus.png",
  sponsorXyz: "/sponsors/xyz.png",
};
